#!/usr/bin/env php
<?php

require_once 'vendor/autoload.php';

use Symfony\Component\Console\Application;
use Plouc\DBVizio\Command\MakeCommand;

$application = new Application();
$application->add(new MakeCommand);
$application->run();